server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  datasource:
    username: root
    password: yuxinwei
    url: jdbc:mysql://localhost:3306/db_lib?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*mapper.xml
  type-aliases-package: net.mynoise.noiseshow.entity